version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - aws --version
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - mvn clean install
      - echo Building Docker image
      - docker build -t merum/automated-search:010 .
      - docker push merum/automated-search:010

  post_build:
    commands:
      - echo Build completed on `date`
