version: 0.2

phases:
  pre_build:
    commands:

      - echo Logging in to DockerHub
      - aws --version
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - REPOSITORY_URI=johnnie3000/camelsearch
  build:
    commands:
      - mvn clean
      - mvn test
      - echo Building Docker image
  post_build:
    commands:
      - echo Build completed on `date`
