version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo Running tests
      - mvn clean
      - echo Building Docker image
      - mvn clean package
      - docker build -t merum/automated-search:$IMAGE_TAG
      - echo Pushing Docker image
      - docker push merum/automated-search:$IMAGE_TAG

post_build:
  commands:
    - echo Build and push completed on `date`
